import { Action } from ".";

export default {
  title: "Components/Action",
  component: Action,
  argTypes: {
    items: {
      options: [
        "chart-content",
        "buttons-title",
        "buttons-hug-toggle",
        "buttons-fill",
        "icon-x3",
        "button-input",
        "link-x3",
        "button-x3",
        "buttons-hug-icon",
        "button-x2-link",
        "button-x2",
        "icon-text",
        "ratings-buttons",
        "button-x2-icon",
        "price-button",
        "button-x2-toogle",
        "buttons-hug",
      ],
      control: { type: "select" },
    },
    direction: {
      options: ["vertical", "horizontal"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    trend: true,
    tagline: "TAGLINE",
    title: "Jasper Doe",
    leadingAction: true,
    button1: false,
    label: true,
    button3: true,
    icon3: true,
    rating: "5.0",
    icon2: true,
    subtitle: "@jasperdoe",
    value: "000",
    tagline1: true,
    button2: true,
    rating1: true,
    caption: true,
    label1: "00",
    icon: true,
    caption1: "Caption ",
    buttons: true,
    subtitle1: true,
    text: "More details...",
    title1: true,
    currency: "RM",
    items: "chart-content",
    direction: "vertical",
    className: {},
    hasSecondaryButton: true,
    buttonSmallLabel: "Button",
    buttonSmallType: "fill",
    buttonSmallCButtonTextClassName: {},
  },
};
